### ISSUE TITLE
test for gw

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_test_kit#7]

**Comment by dsavchenko** [comment]
I added PR for resolver https://github.com/oda-hub/oda-resolver/pull/9 which deals with unexpected connection error

**Comment by dsavchenko** [comment]
@volodymyrss  seems like the resolver is not working in staging again 

I'm not sure how this test kit is intended to be used. Most examples look like pytest tests, but contain some odaexperiment module, which I don't know. Could you clarify?

**Comment by volodymyrss** [comment]
> @volodymyrss seems like the resolver is not working in staging again

I forgot to add the dirty patch in the staging upgrade process. It's there now: https://github.com/oda-hub/frontend-chart/blob/master/make.sh#L231 https://github.com/oda-hub/frontend-chart/blob/master/make.sh#L47
Future staging upgrades will preserve it.
I add https://github.com/oda-hub/frontend-astrooda/issues/132 for a better solution.

> 
> I'm not sure how this test kit is intended to be used. Most examples look like pytest tests, but contain some odaexperiment module, which I don't know. Could you clarify?

For your curiosity, these integration tests are treated like other workflows in ODA KG.
Some intermediate (part outdated and largely out-refactored elsewhere) variation of oda-experiments is here https://github.com/volodymyrss/oda-experiments

The tests are selected, combined with inputs, and executed regularly. 
Results of the outputs are shown in frontend:

![image](https://user-images.githubusercontent.com/3909535/154521815-2c2bb031-fe45-417d-bd89-ad494a653d57.png)

I think I will later add it here https://linked-open-data.space/ with other KG-enabled stuff.

The results are also used to derive further assertions ("facts") about platform, e.g. that a feature works.


edit: to add a test, just create a function which raises an exception in case of an issue. I will then register it as a workflow.
